[test]
pathIgnorePatterns = ["fixtures/**", "fixture/**"]
coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["src/test-setup.ts", "src/__tests__/fixture/**"]
concurrentTestGlob = "off"
onlyFailures = true
preload = ["./src/test-setup.ts"]

[install]
linker = "isolated"

[run]
bun = true
